version: '3.6'

services:
  database:
    image: 'postgres:15-alpine'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRESS_DB: 'db'
    restart: always
    volumes:
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "1333:8080"